services:
  mercury:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=53153
    ports:
      - "${PORT}:53153/udp"
      - "${PORT}:53153/tcp"
    volumes:
      - ./zones:/opt/mercury/zones
