#!/usr/bin/env bash
set -euo pipefail

mkdir -p ~/mercury/zones
cd ~/mercury

compose_uri="https://raw.githubusercontent.com/bernoussama/mercury/main/compose.yaml"
compose="compose.yaml"
curl --fail --location --progress-bar --output "$compose" "$compose_uri" ||
  error "Failed to download bun from \"$compose_uri\""

echo "downloaded mercury image"
read -p "port: " PORT
export PORT

read -p "run as root? (y/n) " yn

if [ "$yn" = "y" ]; then
  echo "running as root"
  sudo docker compose up -d
  echo "done"
fi
